### ISSUE TITLE
R Studio Push Issue

### ISSUE THREAD

**Issue by jessdiallo** [FISH497/assistance#1]
I'm having trouble "pushing" commits from R Studio to my repo on GitHub. 

The attached file shows the error message I get when typing in my GitHub username and password while trying to push commits in R Studio. I can create a new project from a repo and pull files just fine. I can also push commits using my  GitHub Desktop application. So it seems to be a problem with R Studio specifically. I've tried googling the issue without much luck. Is there a way to re-set the GithHub account in R Studio? 
Thanks!

![Screen Shot 2021-01-21 at 12 24 31 PM](https://user-images.githubusercontent.com/45110930/105408323-a8a4ab80-5be3-11eb-8ada-bf8f41cf43f6.png)

**Comment by mdscheuerell** [comment]
Hi Jessica,

What does Git return when you type the following?

```
$ git config --list
```

Also, do you by chance have 2-factor authentication active on GitHub?

**Comment by jessdiallo** [comment]
Hi Mark, 
I did have 2-factor authentication active on Github, so I disabled that and now I can push in R Studio! Thank you! 

I'm not sure if this matters anymore, but this is what shows up when I type that line in my terminal:
credential.helper=osxkeychain
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
user.name=Jessica Diallo
user.email=jodiallo@uw.edu

**Comment by mdscheuerell** [comment]
OK, immediate problem solved.

However, if you want to leave 2FA active (which is a good idea), you can create a "Personal Access Token" (PAT) from within GH and use that as a pwd. In fact, **everyone** will have to start using a PAT in lieu of a pwd on GH come this summer. You can see how to do that [here](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token).

**Comment by jessdiallo** [comment]
Okay, good to know!
