### ISSUE TITLE
Assignment #1 - pushing the .gitignore

### ISSUE THREAD

**Issue by ameliaduvall** [FISH497/assistance#2]
I'm stumped on how to push my .gitignore to my remote repo on GitHub. It's in my files, but if I understand correctly, I cannot push it to my repo unless it's been manipulated. Am I missing something?

**Comment by mdscheuerell** [comment]
When you created the repo in **GitHub** and (presumably) added the `.gitignore` file at the time of creation, it will exist there without issue. If/when you created a project in **RStudio** by cloning the GH repo, the first action was for **Git** to pull everything from GH to your local clone (ie, that you're interacting with via **RStudio**). At that point, the `.gitignore` file will exist in both locations, and there is no need to push it back to GH unless you indeed changed it.

**Comment by ameliaduvall** [comment]
Ok thanks for clarifying!
