### ISSUE TITLE
.DS_Store file

### ISSUE THREAD

**Issue by jessdiallo** [FISH497/assistance#3]
Hi Mark,

A random file called ".DS_Store" appeared in my R Studio Project "Git" window (but not in my "Files" window or in my actual Finder folder). Is this normal and should I be committing and pushing it to my repo on GitHub?
Thanks!

* I wanted to add a label to this issue, but I'm not seeing that option on the righthand side of the screen.

![Screen Shot 2021-01-23 at 11 15 19 AM](https://user-images.githubusercontent.com/45110930/105611792-504ce580-5d6c-11eb-8a56-d5eb388cc012.png)

**Comment by mdscheuerell** [comment]
Hi @jessdiallo. `.DS_Store` is a Mac OS system file, which is related to file tracking and is completely harmless.

If you'd like to avoid having to commit the various versions of `.DS_Store` in the future, you can copy/paste the following block of code into Terminal and hit 'return'.

```
# remove any existing .DS_Store files from the repo
find . -name .DS_Store -print0 | xargs -0 git rm --ignore-unmatch
# specify a global exclusion list
git config --global core.excludesfile ~/.gitignore
# add .DS_Store to the global exclusion list
echo .DS_Store >> ~/.gitignore
```

**Comment by jessdiallo** [comment]
Great, thank you!
