### ISSUE TITLE
Adding assignee to issue

### ISSUE THREAD

**Issue by ameliaduvall** [FISH497/assistance#5]
Hi Mark, I invited you as a collaborator to my Assignment #5 repository because for some reason I am unable to assign you to the issue I created. I tried typing in your username but it will not let me select it (nor anyone else's). I did not run into this issue previously. Any ideas why it might be happening?

**Comment by mdscheuerell** [comment]
Hi Amelia. That was my fault. You can't tag someone in an issue unless they're a collaborator or they've already previously commented themself. So, you did the right thing.
